### ISSUE TITLE
Kaart Street Style does not detect all overlapping buildings

### ISSUE THREAD

**Issue by ralleon** [KaartGroup/Kaart-Styles#5]
JOSM version 14460
https://www.openstreetmap.org/#map=18/16.39442/120.59553

Looking at buildings using JOSM default (Map Paint Style) before 'Validation'
![image](https://user-images.githubusercontent.com/625238/57819116-94c36800-77b9-11e9-91a9-16eed91029e8.png)

Activating Kaart Street Style: detects 2 areas where buildings overlapped 
![image](https://user-images.githubusercontent.com/625238/57819325-89247100-77ba-11e9-902e-a0559ae0c38d.png)

After using 'Validation', JOSM reveals more overlapping buildings
![image](https://user-images.githubusercontent.com/625238/57819345-a6593f80-77ba-11e9-9a47-18f77d57c7cd.png)

Rally De Leon
rally@kaartgroup.com 
Kaart Team Philippines

**Comment by zlavergne** [comment]
@taylorsmock this seems like it might be up your wheelhouse

**Comment by taylorsmock** [comment]
The key word there is "inside". The paintstyle currently only triggers when a building is entirely inside another building. It does not trigger when a building is crossing another building. I can use "⧉", but in my experience, it has been a little buggy (at least in regards to validators).

I'll have a pull request up in a few minutes.

**Comment by zlavergne** [comment]
@ralleon #6 should add a crossing building check but there is a caveat: 
> Please note that the map paint style will not update any
non-edited primitive (so if you fix the issue by moving one of the
buildings, the other building will not update).

I would rely more on the validator for this particular check especially if the project you're working on focuses on buildings 🏘

**Comment by taylorsmock** [comment]
The paint style _will_ show the crossing buildings and new crossing buildings, but it may also show false positives (e.g., you've fixed the issue). There _should not_ be any false negatives. The is much the same situation with the building inside building check. If you fix the issue (e.g., you delete one of the buildings), the other building will still show the building inside building style.

Honestly, I should probably look into the code in JOSM and see if there is a way to trigger a repaint on both objects when something is modified. The hard part would be making it performant (and JOSM already isn't very performant).
